# This file provides instructions for packaging.

`MooseX-ClosedHash`
	perl_version_from m`MooseX::ClosedHash`;
	version_from      m`MooseX::ClosedHash`;
	readme_from       m`MooseX::ClosedHash`;
	requires          p`Moose 2.0400`;
	test_requires     p`Test::More 0.96`;
	test_requires     p`Test::Moose`;
	.

